#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="3.0.5"
URL="http://www.silverstripe.org/assets/releases/SilverStripe-cms-v${VERSION}.tar.gz"

dl $URL /usr/local/src

