#!/bin/sh -ex

DB_NAME=silverstripe
DB_USER=silverstripe
DB_PASS=$(mcookie)

ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/silverstripe

# unpack and set required permissions
tar -zxf $SRC/SilverStripe-*.tar.gz -C $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/SilverStripe-* $WEBROOT
rm -f $SRC/SilverStripe-*.tar.gz
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/assets
chown www-data:www-data $WEBROOT/.htaccess
chown www-data:www-data $WEBROOT/mysite/_config.php

# tweak php.ini
PHPINI=/etc/php5/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 48M|" $PHPINI
sed -i "s|^;date.timezone.*|date.timezone = \"UTC\"|" $PHPINI

# tweak footer
CONF=$WEBROOT/themes/blackcandy/templates/Includes/Footer.ss
sed -i "s|Copyright.*|<a href='http://www.turnkeylinux.org/silverstripe'>SilverStripe Appliance</a> - Powered by <a href='http://www.turnkeylinux.org'>TurnKey Linux</a></p>|" $CONF

# configure apache
a2dissite default
a2ensite silverstripe
a2enmod rewrite

# start services
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# stop services
/etc/init.d/mysql stop

