#!/bin/sh -ex

DB_NAME=silverstripe
DB_USER=silverstripe
DB_PASS=$(mcookie)

ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/silverstripe

# install py-bcrypt (required in inithooks)
pip install py-bcrypt

# unpack and set required permissions
tar -zxf $SRC/SilverStripe-*.tar.gz -C $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/SilverStripe-* $WEBROOT
rm -f $SRC/SilverStripe-*.tar.gz
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/assets
chown www-data:www-data $WEBROOT/.htaccess
chown www-data:www-data $WEBROOT/mysite/_config.php

# tweak php.ini
PHPINI=/etc/php5/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 128M|" $PHPINI
sed -i "s|^;date.timezone.*|date.timezone = \"UTC\"|" $PHPINI

# tweak footer
CONF=$WEBROOT/themes/simple/templates/Includes/Footer.ss
sed -i "s|</footer>|<center><a href='http://www.turnkeylinux.org/silverstripe'>SilverStripe Appliance</a> - Powered by <a href='http://www.turnkeylinux.org'>TurnKey Linux</a></center></footer>|" $CONF

# configure apache
a2dissite 000-default
a2ensite silverstripe
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
URL="http://127.0.0.1"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL ${URL}/install.php --data "db%5Btype%5D=MySQLDatabase&db%5BMySQLDatabase%5D%5Bserver%5D=localhost&db%5BMySQLDatabase%5D%5Busername%5D=$DB_USER&db%5BMySQLDatabase%5D%5Bpassword%5D=$DB_PASS&db%5BMySQLDatabase%5D%5Bdatabase%5D=$DB_NAME&db%5BMSSQLDatabase%5D%5Bserver%5D=localhost&db%5BMSSQLDatabase%5D%5Busername%5D=root&db%5BMSSQLDatabase%5D%5Bpassword%5D=&db%5BMSSQLDatabase%5D%5Bdatabase%5D=SS_mysite&db%5BPostgreSQLDatabase%5D%5Bserver%5D=localhost&db%5BPostgreSQLDatabase%5D%5Busername%5D=root&db%5BPostgreSQLDatabase%5D%5Bpassword%5D=&db%5BPostgreSQLDatabase%5D%5Bdatabase%5D=SS_mysite&db%5BSQLiteDatabase%5D%5Bpath%5D=%2Fvar%2Fwww%2Fsilverstripe%2Fassets%2F.db&db%5BSQLiteDatabase%5D%5Bdatabase%5D=SS_mysite&admin%5Busername%5D=$EMAIL&admin%5Bpassword%5D=$ADMIN_PASS&locale=en_US&template=simple&go=Installing+SilverStripe..."

$CURL ${URL}/InstallerTest/testrewrite
$CURL ${URL}/home/successfullyinstalled?flush=1

rm -f /tmp/cookie
rm -f $WEBROOT/install.php

# set site name
$MYSQL_BATCH --execute "UPDATE $DB_NAME.SiteConfig SET Title=\"TurnKey SilverStripe\" WHERE ClassName=\"SiteConfig\";"
$MYSQL_BATCH --execute "UPDATE $DB_NAME.SiteConfig SET Tagline=NULL WHERE ClassName=\"SiteConfig\";"

# chmod sensitive files
chmod 640 $WEBROOT/mysite/_config.php

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

