#!/bin/sh -ex

DB_NAME=silverstripe
DB_USER=silverstripe
DB_PASS=$(mcookie)

ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/silverstripe

VERSION=4.5.2

# unpack and set required permissions
cd /var/www
composer create-project silverstripe/installer silverstripe

cp $WEBROOT/.env.example $WEBROOT/.env
ENV=$WEBROOT/.env
sed -i "s/^\(SS_DATABASE_USERNAME=\).*$/\1\"$DB_USER\"/" $ENV
sed -i "s/^\(SS_DATABASE_PASSWORD=\).*$/\1\"$DB_PASS\"/" $ENV
sed -i "s/^\(SS_DATABASE_NAME=\).*$/\1\"$DB_NAME\"/" $ENV
echo "SS_DEFAULT_ADMIN_USERNAME=\"admin\"" >> $ENV
echo "SS_DEFAULT_ADMIN_PASSWORD=\"$ADMIN_PASS\"" >> $ENV
chown -R www-data:www-data $WEBROOT

# tweak php.ini
PHPINI=/etc/php/7.3/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 128M|" $PHPINI
sed -i "s|^;date.timezone.*|date.timezone = \"UTC\"|" $PHPINI

# tweak footer
CONF=$WEBROOT/themes/simple/templates/Includes/Footer.ss
sed -i "s|</footer>|<center><a href='https://www.turnkeylinux.org/silverstripe'>SilverStripe Appliance</a> - Powered by <a href='https://www.turnkeylinux.org'>TurnKey Linux</a></center></footer>|" $CONF

# configure apache
a2dissite 000-default
a2ensite silverstripe
a2enmod rewrite

# start services
service mysql start
service apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

cd $WEBROOT
./vendor/bin/sake dev/build

# set site name
#$MYSQL_BATCH --execute "UPDATE $DB_NAME.SiteConfig SET Title=\"TurnKey SilverStripe\" WHERE ClassName=\"SiteConfig\";"
#$MYSQL_BATCH --execute "UPDATE $DB_NAME.SiteConfig SET Tagline=NULL WHERE ClassName=\"SiteConfig\";"

# chown sensitive files
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/public/assets
chown www-data:www-data $WEBROOT/public/.htaccess
chown www-data:www-data $WEBROOT/app/_config.php
chown www-data:www-data $WEBROOT/public/index.php
chown www-data:www-data $WEBROOT/.env
chown www-data:www-data $WEBROOT/app/_config/theme.yml

# chmod sensitive files
chmod 640 $WEBROOT/app/_config.php

# stop services
service mysql stop
service apache2 stop
