#!/bin/bash -e
# regenerate silverstripe mysql password

. /etc/default/inithooks

CONF=/var/www/silverstripe/.env
PASSWORD=$(mcookie)

sed -i "s|SS_DATABASE_PASSWORD.*|SS_DATABASE_PASSWORD=\"$PASSWORD\"|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=silverstripe --pass="$PASSWORD"

