#!/bin/bash -e
# regenerate silverstripe mysql password

. /etc/default/inithooks

CONF=/var/www/silverstripe/mysite/_config.php
PASSWORD=$(mcookie)

sed -i "s|password.*|password\" => '$PASSWORD',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=silverstripe --pass="$PASSWORD"

